import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapContainer,TileLayer,CircleMarker,Popup,Polyline,ZoomControl} from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import {ShieldCheck,Satellite,RadioTower,CloudRain,Mountain,Activity,RefreshCw,Play,TriangleAlert,MessageSquare,MapPin,Wind, Droplets, Wifi, CheckCircle2, XCircle, ChevronRight, Phone, Zap, Waves, BrainCircuit, Eye, Gauge, Thermometer, Sun, Moon, Cloud, CloudLightning, LocateFixed, Layers, Navigation, Volume2, Sparkles, Menu, X, ArrowUpRight, PlayCircle, ChevronLeft, Maximize2, Pause, BookOpen} from 'lucide-react';
import './style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const IMG1='https://commons.wikimedia.org/wiki/Special:Redirect/file/Monsoon_in_Himalayas.jpg';
const IMG2='https://commons.wikimedia.org/wiki/Special:Redirect/file/Cloudscape_over_the_Himalayan_region,_Himachal_Pradesh,_India.jpg';
const IMD_SAT='https://mausam.imd.gov.in/imd_latest/contents/rapidscan.php';

function App(){
 const [tab,setTab]=useState('overview'),[data,setData]=useState({locations:[],alerts:[]}),[weather,setWeather]=useState(null),[sensors,setSensors]=useState(null),[config,setConfig]=useState(null),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[phone,setPhone]=useState(''),[sms,setSms]=useState(null),[clock,setClock]=useState(new Date()),[theme,setTheme]=useState('dark'),[mobileNav,setMobileNav]=useState(false);
 const load=async()=>{try{const [r,w,s,c]=await Promise.all([fetch(API+'/api/risk/current'),fetch(API+'/api/weather/forecast'),fetch(API+'/api/sensors/health').catch(()=>null),fetch(API+'/api/config')]);setData(await r.json());setWeather(await w.json());if(s) setSensors(await s.json());setConfig(await c.json())}catch(e){}};
 useEffect(()=>{load();const t=setInterval(()=>{fetch(API+'/api/simulation/tick',{method:'POST'}).then(r=>r.json()).then(setData).catch(()=>{});load()},8000);const c=setInterval(()=>setClock(new Date()),1000);return()=>{clearInterval(t);clearInterval(c)}},[]);
 const sim=async(path)=>{setBusy(true);const r=await fetch(API+path,{method:'POST'});setData(await r.json());await load();setBusy(false)};
 const loc=data.locations||[], counts=useMemo(()=>Object.fromEntries(['SAFE','WATCH','WARNING','EVACUATE'].map(x=>[x,loc.filter(v=>v.risk.level===x).length])),[loc]);
 const current=loc[2]||loc[0];
 const sendTest=async()=>{if(!phone)return;const r=await fetch(API+'/api/notifications/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone})});setSms(await r.json())};
 return <div className={'app '+theme}>
  <header className="topbar"><div className="brand"><div className="logo"><ShieldCheck/></div><div><b>GEO SHIELD <span>AI</span></b><small>HIMALAYAN HAZARD INTELLIGENCE</small></div></div><div className="location-chip"><LocateFixed size={13}/><span>Indian Himalayan Region</span><ChevronRight size={13}/></div><div className="topstatus"><span className="pulse"></span>LIVE SIMULATION <span className="divider"></span>{clock.toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit'})} IST <button aria-label="Refresh" onClick={load}><RefreshCw size={15}/></button><button aria-label="Toggle theme" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={15}/>:<Moon size={15}/>}</button></div><button className="mobile-menu" onClick={()=>setMobileNav(!mobileNav)}>{mobileNav?<X/>:<Menu/>}</button></header>
  <nav className={mobileNav?'open':''}>{[['presentation','Presentation',PlayCircle],['overview','Command Center',ShieldCheck],['forecast','Weather AI',CloudRain],['satellite','Satellite',Satellite],['sensors','Sensors',RadioTower],['alerts','Alerts & SMS',MessageSquare],['landslides','Landslide AI',Mountain],['sih','SIH Blueprint',BrainCircuit]].map(([k,l,I])=><button key={k} className={tab===k?'active':''} onClick={()=>{setTab(k);setMobileNav(false)}}><I size={14}/>{l}{k==='alerts'&&data.alerts?.length?<i>{data.alerts.length}</i>:null}</button>)}</nav>
  {tab==='presentation'&&<Presentation onClose={()=>setTab('overview')}/>}
  {tab==='overview'&&<Overview loc={loc} counts={counts} sensors={sensors} data={data} setSelected={setSelected} sim={sim} busy={busy} current={current}/>} 
  {tab==='forecast'&&<Forecast weather={weather} loc={loc}/>} 
  {tab==='satellite'&&<SatelliteView loc={loc} image={IMG2}/>} 
  {tab==='sensors'&&<SensorPage sensors={sensors} loc={loc}/>} 
  {tab==='alerts'&&<AlertPage alerts={data.alerts||[]} phone={phone} setPhone={setPhone} sendTest={sendTest} sms={sms} config={config}/>}
  {tab==='landslides'&&<LandslidePage loc={loc} sim={sim} busy={busy} setSelected={setSelected}/>} 
  {tab==='sih'&&<SIHBlueprint/>}
  {selected&&<Detail v={selected} close={()=>setSelected(null)}/>}<footer>GEO SHIELD AI · DEMO / SIMULATED DATA · Not an official government warning system · Model thresholds are demonstration values.</footer>
 </div>
}

function Presentation({onClose}){
 const slides=Array.from({length:6},(_,i)=>`/presentation/slide-${i+1}.png`);
 const [i,setI]=useState(0),[playing,setPlaying]=useState(false);
 useEffect(()=>{if(!playing)return;const t=setInterval(()=>setI(x=>(x+1)%slides.length),7000);return()=>clearInterval(t)},[playing]);
 useEffect(()=>{const h=e=>{if(e.key==='Escape')onClose();if(e.key==='ArrowRight')setI(x=>(x+1)%slides.length);if(e.key==='ArrowLeft')setI(x=>(x-1+slides.length)%slides.length);if(e.key===' ') {e.preventDefault();setPlaying(x=>!x)}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[onClose]);
 return <div className="presentation-overlay"><div className="presentation-shell original-presentation"><div className="presentation-top"><div><span className="pres-dot"></span><b>ORIGINAL SIH PRESENTATION</b><small>· GEO SHIELD AI · 6 SLIDES</small></div><div className="pres-controls"><button onClick={()=>setPlaying(x=>!x)} title={playing?'Pause':'Play'}>{playing?<Pause size={16}/>:<PlayCircle size={16}/>}</button><button onClick={()=>document.documentElement.requestFullscreen?.()} title="Fullscreen"><Maximize2 size={16}/></button><button onClick={onClose} title="Close">×</button></div></div><div className="pres-progress"><span style={{width:`${((i+1)/slides.length)*100}%`}}></span></div><div className="original-slide-stage"><img className="original-slide-image" src={slides[i]} alt={`Original Geo Shield AI SIH presentation slide ${i+1}`} /></div><div className="presentation-bottom"><button onClick={()=>setI(x=>(x-1+slides.length)%slides.length)}><ChevronLeft size={18}/> Previous</button><div className="pres-counter">{i+1} / {slides.length}</div><button onClick={()=>setI(x=>(x+1)%slides.length)}>Next <ChevronRight size={18}/></button></div></div></div>
}

function Overview({loc,counts,sensors,data,setSelected,sim,busy,current}){
 const [layer,setLayer]=useState('risk'); const [radar,setRadar]=useState(true); const [auto,setAuto]=useState(true);
 const riskColor=(v)=>v.risk.level.toLowerCase();
 const weatherStats={temp:Math.round(current?.temp||18),humidity:Math.round(current?.humidity||84),wind:Math.round(4+((current?.rain||40)/30)),pressure:1002+Math.round((current?.soil||55)/15),visibility:Math.max(1,8-Math.round((current?.rain||40)/22)),aqi:35+Math.round((current?.humidity||80)/8)};
 return <main>
  <section className="home-banner" aria-label="Geo Shield AI mission banner"><img src="/images/geo-shield-banner.png" alt="Geo Shield AI disaster intelligence banner" /><div className="home-banner-overlay"><span><span className="pulse"></span> HIMALAYAN EARLY-WARNING COMMAND</span><b>Predict · Prepare · Protect</b><small>Multi-source intelligence for flash floods and landslides</small></div></section>
  <section className="command-hero">
   <div className="hero-copy"><div className="eyebrow"><Sparkles size={12}/> AI-POWERED DISASTER INTELLIGENCE · 24/7 SIMULATION</div><h1>See the storm <em>before it becomes a disaster.</em></h1><p>Geo Shield AI fuses simulated weather, terrain, river, soil, sensor and satellite signals into a live, explainable risk picture for Himalayan communities.</p><div className="hero-actions"><button className="primary" disabled={busy} onClick={()=>sim('/api/simulation/flash-flood')}><Play size={16}/>Run Flash-Flood Scenario</button><button className="ghost" onClick={()=>sim('/api/simulation/landslide')}><Mountain size={16}/>Landslide Scenario</button><button className="ghost" onClick={()=>sim('/api/simulation/normal')}>Reset</button></div><div className="trust-line"><span><span className="pulse"></span> DATA STREAMS ACTIVE</span><span>AI ENGINE v1.0</span><span>LAST SYNC 8 SEC AGO</span></div></div>
   <div className="weather-hero" style={{backgroundImage:`linear-gradient(110deg,#061713ee 0%,#06171377 55%,#06171322),url('${IMG1}')`}}><div className="weather-top"><div><small>HIMALAYAN MONSOON</small><b>{current?.name||'Riverbend'}</b></div><div className={'big-risk '+riskColor(current||{risk:{level:'WATCH'}})}>{current?.risk?.level||'WATCH'}</div></div><div className="weather-main"><div className="temp"><CloudRain/><strong>{weatherStats.temp}°</strong><span>Cloudy rain</span></div><div className="hero-stat-grid"><span><Thermometer/>Feels like <b>{weatherStats.temp+2}°</b></span><span><Droplets/>Humidity <b>{weatherStats.humidity}%</b></span><span><Wind/>Wind <b>{weatherStats.wind} km/h</b></span><span><Eye/>Visibility <b>{weatherStats.visibility} km</b></span></div></div><div className="weather-footer"><span>Rain chance <b>{Math.min(98,Math.round((current?.rain||40)*.8))}%</b></span><span>Elevation <b>{current?.elevation||1320} m</b></span><span>Risk score <b>{current?.risk?.score||0}/100</b></span></div></div>
  </section>
  <div className="disclaimer"><TriangleAlert size={16}/><span><b>Decision-support prototype.</b> All values are simulated automatically. It does not replace IMD, NDRF, DDMA, SDMA or other official warnings.</span><span className="demo-pill">DEMO MODE</span></div>
  <section className="kpis"><Kpi icon={<MapPin/>} label="Monitored Villages / Wards" value={loc.length} meta="HYPER-LOCAL"/><Kpi icon={<TriangleAlert/>} label="Active Alerts" value={counts.WARNING+counts.EVACUATE} meta="WARNING + EVACUATE"/><Kpi icon={<Zap/>} label="Evacuation Zones" value={counts.EVACUATE} meta="SAFETY PRIORITY"/><Kpi icon={<RadioTower/>} label="Online IoT Sensors" value={sensors?.online??46} meta={`${sensors?.total??52} SIMULATED`}/><Kpi icon={<Activity/>} label="Warning Lead Time" value="37m" meta="SIMULATION METRIC"/></section>
  <section className="why-use"><div className="why-head"><div><div className="eyebrow"><ShieldCheck size={12}/> WHY GEO SHIELD AI</div><h2>Built for the gap between a weather forecast and a local evacuation decision.</h2><p>Geo Shield AI is designed around hyper-local risk synthesis: rainfall, soil saturation, slope exposure, river level, ground movement, historical hazard context and remote-sensing signals are presented together instead of as isolated dashboards.</p></div><div className="why-badge"><BrainCircuit/><b>MULTI-HAZARD</b><span>One operational picture</span></div></div><div className="unique-grid"><div><b>01 · HYPER-LOCAL</b><span>Village / ward level risk instead of only broad regional weather information.</span></div><div><b>02 · EXPLAINABLE</b><span>Every escalation shows the physical signals that pushed the score upward.</span></div><div><b>03 · MULTI-SOURCE</b><span>Weather + IoT + terrain + river + satellite + historical context in one workflow.</span></div><div><b>04 · ACTIONABLE</b><span>Risk states connect directly to shelters, evacuation guidance and SMS escalation.</span></div><div><b>05 · FAILURE-AWARE</b><span>Sensor health and data coverage are visible so missing data is not mistaken for safety.</span></div><div><b>06 · DEMO-READY</b><span>Deterministic simulations show how a normal situation can evolve into warning and evacuation.</span></div></div><div className="optional-features"><span>OPTIONAL NEXT FEATURES</span><button type="button">CAP-based alerts</button><button type="button">WhatsApp / Push</button><button type="button">Offline field PWA</button><button type="button">InSAR deformation</button><button type="button">Road closure layer</button><button type="button">Shelter routing</button></div></section>
  <section className="source-strip"><div className="source-strip-title"><Sparkles size={14}/> MULTI-SOURCE DATA FUSION</div><div><CloudRain/> Rainfall</div><div><Droplets/> Soil Moisture</div><div><Mountain/> Slope Stability</div><div><Waves/> River Level</div><div><RadioTower/> Real-time IoT</div><div><Satellite/> Satellite / Remote Sensing</div><div><Activity/> Historical Events</div></section>
  <section className="dashboard-grid">
   <div className="panel map-panel"><div className="panel-head"><div><h2>India Hazard Intelligence Map</h2><span>Real OpenStreetMap geography · Himalayan risk overlay · clickable villages</span></div><div className="map-tools"><button className={layer==='risk'?'sel':''} onClick={()=>setLayer('risk')}><TriangleAlert size={12}/>Risk</button><button className={layer==='rain'?'sel':''} onClick={()=>setLayer('rain')}><CloudRain size={12}/>Rain</button><button className={layer==='satellite'?'sel':''} onClick={()=>setLayer('satellite')}><Satellite size={12}/>Satellite</button></div></div><div className="real-map-wrap"><IndiaMap loc={loc} layer={layer} setSelected={setSelected}/><div className="map-overlay-card"><span><span className="pulse"></span> LIVE MODEL LAYER</span><b>{layer==='rain'?'Rainfall intensity':layer==='satellite'?'Satellite coverage':'Village risk score'}</b><small>Map data © OpenStreetMap contributors</small></div><div className="scan-corner"><span>SCANNING</span><i></i><i></i><i></i></div></div></div>
   <div className="side-stack">
    <div className="panel weather-widgets"><div className="panel-head"><div><h2>Weather Station</h2><span>{current?.name||'Riverbend'} · synthetic feed</span></div><CloudRain size={18}/></div><div className="widget-grid"><WeatherWidget icon={<Eye/>} label="Visibility" value={`${weatherStats.visibility} km`} sub="Good"/><WeatherWidget icon={<Gauge/>} label="Pressure" value={`${weatherStats.pressure} mb`} sub="Rising"/><WeatherWidget icon={<Wind/>} label="Wind" value={`${weatherStats.wind} km/h`} sub="Light air"/><WeatherWidget icon={<Droplets/>} label="Humidity" value={`${weatherStats.humidity}%`} sub="Very humid"/><WeatherWidget icon={<Zap/>} label="AQI" value={weatherStats.aqi} sub="Moderate"/><WeatherWidget icon={<Moon/>} label="Moon" value="72%" sub="Waxing"/></div></div>
    <div className="panel threat-panel"><div className="panel-head"><div><h2>AI Threat Index</h2><span>Combined hazard pressure</span></div><BrainCircuit size={18}/></div><ThreatGauge score={current?.risk?.score||0}/><div className="threat-copy"><b>{current?.risk?.level||'WATCH'}</b><span>{current?.risk?.simple_explanation||'Monitoring current conditions.'}</span></div></div>
   </div>
  </section>
  <section className="lower-grid"><div className="panel"><div className="panel-head"><div><h2>Village Risk Feed</h2><span>Automatically refreshed every 8 seconds</span></div><span className="live"><i></i>LIVE</span></div>{loc.map(v=><div className="risk-row" key={v.id} onClick={()=>setSelected(v)}><div className={'status '+riskColor(v)}>{v.risk.level}</div><div className="row-main"><b>{v.name}</b><small>{v.region} · {v.risk.coverage}% coverage</small></div><div className="mini-weather"><CloudRain size={12}/>{v.rain} mm/h</div><strong>{v.risk.score}</strong><ChevronRight size={14}/></div>)}</div>
   <div className="panel"><div className="panel-head"><div><h2>Storm Radar</h2><span>Synthetic precipitation movement</span></div><Navigation size={17}/></div><RadarChart loc={loc}/><div className="radar-legend"><span><i></i>Low</span><span><i></i>Watch</span><span><i></i>Heavy</span><span><i></i>Extreme</span></div></div></section>
  <section className="solution-grid"><RainMeasurement current={current}/><div className="panel fusion-panel"><div className="panel-head"><div><h2>Hyper-local Prediction Pipeline</h2><span>Raw signals → validated features → village/ward action</span></div><BrainCircuit/></div><div className="pipeline"><div><span>01</span><b>COLLECT</b><small>Rainfall · soil · slope · river · IoT · satellite · history</small></div><div><span>02</span><b>VALIDATE</b><small>Freshness · anomalies · sensor health · coverage</small></div><div><span>03</span><b>PREDICT</b><small>Flash flood + landslide + combined risk</small></div><div><span>04</span><b>WARN</b><small>Village / ward level alert + explanation + lead time</small></div><div><span>05</span><b>ACT</b><small>Shelter guidance · responder workflow · SMS</small></div></div></div></section><section className="statement-band"><div><b>BACKGROUND</b><span>Hilly states in India can experience flash floods and landslides with very short warning times. Geo Shield AI is designed around earlier detection and hyper-local risk visibility.</span></div><div><b>EXPECTED SOLUTION</b><span>Integrates rainfall, soil moisture, slope stability, historical disaster data and real-time IoT inputs to issue actionable village/ward warnings and evacuation preparation guidance.</span></div></section>
  <section className="landslide-teaser panel"><div className="panel-head"><div><h2>Landslide Detection & Simulation</h2><span>Rainfall-triggered slope risk · ground movement · soil saturation</span></div><Mountain size={18}/></div><div className="landslide-teaser-body"><div className="slope-scan"><div className="slope-grid"></div><div className="slope-line"></div><div className="slope-target"><span></span><b>SLOPE SCAN</b><small>AI deformation monitor</small></div></div><div className="landslide-copy"><div className="landslide-metrics"><span><b>{Math.round((current?.risk?.landslide_score)||0)}</b><small>LANDSLIDE SCORE</small></span><span><b>{current?.slope||0}°</b><small>AVG SLOPE</small></span><span><b>{current?.soil||0}%</b><small>SOIL SATURATION</small></span><span><b>{current?.ground||35}%</b><small>GROUND MOVEMENT</small></span></div><p>Detection combines rainfall accumulation, slope exposure, soil saturation, historical hazard context and simulated ground movement. Use the scenario to demonstrate escalation before a slope-failure event.</p><button className="primary" disabled={busy} onClick={()=>sim('/api/simulation/landslide')}><Mountain size={15}/>Run Landslide Detection Simulation</button></div></div></section>
  <section className="lower-grid"><div className="panel"><div className="panel-head"><div><h2>AI Risk Drivers</h2><span>Explainable hybrid engine</span></div><BrainCircuit size={19}/></div><div className="drivers">{['Rainfall intensity','Soil saturation','Slope exposure','River level','Ground movement'].map((x,i)=>{const vals=[78,68,57,63,41];return <div key={x}><span>{x}</span><div className="driverbar"><i style={{width:`${vals[i]}%`}}></i></div><b>{vals[i]}%</b></div>})}</div></div><div className="panel"><div className="panel-head"><div><h2>Incident Timeline</h2><span>{data.scenario||'NORMAL'} simulation</span></div><MessageSquare size={18}/></div><Timeline alerts={data.alerts||[]}/></div></section>
 </main>
}
function IndiaMap({loc,layer,setSelected}){return <MapContainer center={[30.4,80.2]} zoom={5.5} minZoom={4} maxZoom={9} scrollWheelZoom={true} zoomControl={false} className="india-leaflet-map"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><ZoomControl position="bottomleft"/><Polyline positions={[[35.5,74.2],[33.8,76.4],[32.4,78.1],[30.8,79.8],[29.3,81.7],[27.7,84.5],[27.3,88.6]]} pathOptions={{color:'#67d7a5',weight:2,dashArray:'5 7',opacity:.7}}/>{loc.map(v=>{const value=layer==='rain'?v.rain:layer==='satellite'?v.risk.coverage:v.risk.score;const color=v.risk.level==='EVACUATE'?'#ff5b61':v.risk.level==='WARNING'?'#ffad4d':v.risk.level==='WATCH'?'#e5cf5c':'#61d4a5';return <CircleMarker key={v.id} center={[v.lat,v.lng]} radius={Math.max(7,Math.min(15,6+value/12))} pathOptions={{color,fillColor:color,fillOpacity:.78,weight:2}} eventHandlers={{click:()=>setSelected(v)}}><Popup><div className="map-popup"><b>{v.name}</b><span>{v.region}</span><strong>{v.risk.level} · {v.risk.score}/100</strong><small>Rain {v.rain} mm/h · Soil {v.soil}% · Slope {v.slope}°</small></div></Popup></CircleMarker>})}</MapContainer>}

function RainMeasurement({current}){const base=Math.max(2,current?.rain||42);const vals=[['15 MIN',base*.22],['1 HOUR',base],['3 HOURS',base*2.15],['6 HOURS',base*3.55],['24 HOURS',base*6.8]].map(([l,v])=>[l,Math.round(v)]);return <div className="rain-measure"><div className="rain-measure-head"><div><h2>Rainfall Measurement</h2><span>Automatic synthetic rain gauge · {current?.name||'Himalayan station'}</span></div><CloudRain/></div><div className="rain-reading"><strong>{Math.round(base)}</strong><span>mm/h</span><b>LIVE INTENSITY</b></div><div className="rain-bars">{vals.map(([l,v],i)=><div key={l}><div className="rain-bar"><i style={{height:`${Math.min(100,18+v/1.3)}%`}}></i></div><b>{v}</b><small>{l}</small></div>)}</div><div className="rain-foot"><span><span className="pulse"></span> Gauge updating automatically</span><span>Thresholds configurable by authorized agencies</span></div></div>}

function Kpi({icon,label,value,meta}){return <div className="kpi"><div className="kpi-icon">{icon}</div><small>{label}</small><strong>{value}</strong><span>{meta}</span></div>}
function WeatherWidget({icon,label,value,sub}){return <div className="weather-widget"><div>{icon}</div><span>{label}</span><b>{value}</b><small>{sub}</small></div>}
function ThreatGauge({score}){const angle=-90+(Math.max(0,Math.min(100,score))*180/100);return <div className="gauge"><div className="gauge-track"></div><div className="gauge-fill" style={{transform:`rotate(${angle}deg)`}}></div><div className="gauge-center"><strong>{score}</strong><small>/100</small></div><span className="gauge-low">SAFE</span><span className="gauge-high">EXTREME</span></div>}
function RadarChart({loc}){const vals=(loc||[]).slice(0,7).map(v=>Math.max(10,Math.min(100,v.rain)));while(vals.length<7)vals.push(30);const points=vals.map((v,i)=>{const a=(-90+i*60)*Math.PI/180;const r=55+(v/100)*50;return `${100+Math.cos(a)*r},${85+Math.sin(a)*r}`}).join(' ');return <div className="radar-chart"><div className="radar-ring r1"></div><div className="radar-ring r2"></div><div className="radar-ring r3"></div><div className="radar-scan"></div><svg viewBox="0 0 200 170"><polygon points="100,25 148,53 148,110 100,140 52,110 52,53" fill="none" stroke="rgba(132,222,186,.18)"/><polygon points={points} fill="rgba(94,206,166,.18)" stroke="#72dcae" strokeWidth="2"/></svg><div className="radar-center"><span></span></div></div>}
function Timeline({alerts}){let items=[['14:00','Satellite cloud anomaly detected'],['14:07','Rainfall model updated'],['14:16','Soil saturation rising'],['14:27','Village enters WATCH'],['14:35','Risk crosses WARNING'],['14:41','EVACUATION protocol triggered']];if(alerts[0])items[5]=['NOW',`${alerts[0].village} · ${alerts[0].level} alert generated`];return <div className="timeline">{items.map((x,i)=><div className="timeline-item" key={i}><b>{x[0]}</b><i></i><span>{x[1]}</span></div>)}</div>}
function Forecast({weather,loc}){const [focus,setFocus]=useState(0);return <main><section className="page-head"><div><div className="eyebrow">GENERATIVE WEATHER SIMULATION</div><h1>Himalayan Weather AI</h1><p>Feels like a premium weather console: forecast cards, atmospheric metrics, radar and mountain imagery, all driven by synthetic data.</p></div><div className="ai-badge"><BrainCircuit/>AI FORECAST ENGINE</div></section><div className="weather-console" style={{backgroundImage:`linear-gradient(100deg,#071813ee,#07181355),url('${IMG2}')`}}><div className="console-location"><small>INDIAN HIMALAYAN REGION</small><b>Monsoon corridor</b><span>Himachal · Uttarakhand · Sikkim · high-altitude valleys</span></div><div className="console-temp"><CloudRain/><strong>{loc[0]?.temp||18}°</strong><span>Cloudy / rain</span></div><div className="console-meta"><span><Droplets/>Rain <b>{loc[0]?.rain||42} mm/h</b></span><span><Wind/>Wind <b>7 km/h</b></span><span><Eye/>Visibility <b>3 km</b></span><span><Gauge/>Pressure <b>1003 mb</b></span></div></div><div className="forecast-tabs"><button className="active">Today</button><button>Hourly</button><button>7 Day</button><button>Risk Outlook</button></div><div className="forecast-grid">{(weather?.forecast||[]).map((x,i)=><button className={'forecast-card '+(focus===i?'selected':'')} key={i} onClick={()=>setFocus(i)}><small>{x.day}</small><div className="forecast-icon">{x.condition.includes('Thunder')?<CloudLightning/>:x.condition.includes('rain')?<CloudRain/>:x.condition.includes('Cloud')?<Cloud/>:<Wind/>}</div><strong>{x.temp}°</strong><span>{x.condition}</span><b>{x.chance}% rain</b><small>{x.rain_mm} mm simulated</small></button>)}</div><div className="forecast-bottom"><div className="hourly-card"><div className="panel-head"><div><h2>24-hour rain pulse</h2><span>Tap points for detail</span></div><Activity size={18}/></div><RainCurve/></div><div className="image-strip"><div style={{backgroundImage:`url('${IMG1}')`}}><b>Monsoon cloud wall</b><span>High precipitation context</span></div><div style={{backgroundImage:`url('${IMG2}')`}}><b>Mountain cloud deck</b><span>Simulated satellite context</span></div></div></div><p className="source-note">Forecast values are randomly generated for demonstration and are not real weather forecasts.</p></main>}
function RainCurve(){return <div className="rain-curve"><svg viewBox="0 0 720 210" preserveAspectRatio="none"><defs><linearGradient id="rainFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#61d4a5" stopOpacity=".35"/><stop offset="1" stopColor="#61d4a5" stopOpacity="0"/></linearGradient></defs><path d="M0 170 C55 145,90 152,130 130 S220 145,270 105 S350 112,390 82 S470 96,520 70 S600 90,720 40 L720 210 L0 210Z" fill="url(#rainFill)"/><path d="M0 170 C55 145,90 152,130 130 S220 145,270 105 S350 112,390 82 S470 96,520 70 S600 90,720 40" fill="none" stroke="#72dcae" strokeWidth="3"/></svg><div className="curve-labels"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>24:00</span></div></div>}
function SatelliteView({loc,image}){
 const [mode,setMode]=useState('cloud');
 const [frame,setFrame]=useState(0);
 const [playing,setPlaying]=useState(true);
 useEffect(()=>{
   if(!playing) return;
   const t=setInterval(()=>setFrame(x=>(x+1)%4),3000);
   return()=>clearInterval(t)
 },[playing]);
 const frames=[image,image,IMG1,image];
 const frameLabels=['Latest model frame','Cloud-top analysis','Monsoon context','Himalayan moisture pass'];
 const modeText={cloud:'Infrared cloud structure',moisture:'Water-vapour interpretation',terrain:'Terrain / slope context'};
 return <main>
  <section className="page-head">
   <div>
    <div className="eyebrow">REMOTE SENSING · INSAT / MOSDAC READY</div>
    <h1>Satellite Intelligence</h1>
    <p>Animated remote-sensing console with a local fallback. The broken MOSDAC iframe has been removed; official satellite services open safely in a new tab.</p>
   </div>
   <div className="sat-status live"><Satellite/> SATELLITE MONITOR · FRAME {String(frame+1).padStart(2,'0')}</div>
  </section>
  <div className="sat-live-shell">
   <div className="sat-live-frame">
    <div className="sat-source"><span>INDIA · HIMALAYAN SECTOR</span><b>INSAT REMOTE SENSING</b><small>{modeText[mode]} · {frameLabels[frame]}</small></div>
    <div className="sat-fallback" style={{backgroundImage:`linear-gradient(90deg,#071813aa,#07181322),url('${frames[frame]}')`}}></div>
    <div className="sat-live-vignette"></div>
    <div className="live-scan"></div>
    <div className="scan-grid"></div>
    <div className="sat-target"><span></span><b>HIMALAYAN ARC</b><small>AI scan zone</small></div>
    <div className="sat-clock">AUTO FRAME · {new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit'})} IST</div>
    <div className="sat-live-controls">
      <button className={mode==='cloud'?'active':''} onClick={()=>setMode('cloud')}>Cloud</button>
      <button className={mode==='moisture'?'active':''} onClick={()=>setMode('moisture')}>Moisture</button>
      <button className={mode==='terrain'?'active':''} onClick={()=>setMode('terrain')}>Terrain</button>
      <button className={playing?'active':''} onClick={()=>setPlaying(v=>!v)}>{playing?'Pause Scan':'Play Scan'}</button>
      <a href={IMD_SAT} target="_blank" rel="noreferrer">Open IMD Rapid Scan ↗</a>
    </div>
    <div className={'sat-filter '+mode}></div>
    <div className="sat-frame-label"><span className="pulse"></span> DEMO REMOTE-SENSING FRAME · NOT A LIVE GOVERNMENT FEED</div>
   </div>
   <div className="sat-live-side">
    <div className="panel sat-panel">
     <h2>Live Detection Queue</h2>
     {[['Cloud mass','HIGH','82%'],['Rainfall signature','ELEVATED','74%'],['Soil moisture','WATCH','68%'],['Slope movement','MONITOR','43%'],['Snow / ice','LOW','16%']].map(x=><div className="detect" key={x[0]}><div><b>{x[0]}</b><small>AI interpretation layer</small></div><span>{x[1]}</span><strong>{x[2]}</strong></div>)}
     <div className="sat-foot"><Satellite size={16}/> Official satellite services are linked below; this visual layer is safe demo data.</div>
    </div>
    <div className="panel scan-status">
     <div><span className="scan-dot"></span><b>SCANNING HIMALAYAN ARC</b></div>
     <p>Continuous scan animation shows how Geo Shield AI can process satellite observations alongside rainfall, soil, slope and IoT signals.</p>
     <div className="official-links">
      <a href={IMD_SAT} target="_blank" rel="noreferrer">IMD INSAT-3DR Rapid Scan ↗</a>
      <a href="https://www.mosdac.gov.in/" target="_blank" rel="noreferrer">MOSDAC / ISRO ↗</a>
     </div>
    </div>
   </div>
  </div>
 </main>
}
function SensorPage({sensors}){return <main><section className="page-head"><div><div className="eyebrow">IOT TELEMETRY</div><h1>Sensor Network</h1><p>Fake field sensors generate changing readings so the full alert pipeline can be demonstrated.</p></div><div className="network"><Wifi/> {sensors?.online??46}/{sensors?.total??52} ONLINE</div></section><div className="sensor-summary"><Kpi icon={<RadioTower/>} label="Total Sensors" value={sensors?.total??52} meta="SIMULATED"/><Kpi icon={<CheckCircle2/>} label="Online" value={sensors?.online??46} meta="HEALTHY"/><Kpi icon={<XCircle/>} label="Offline" value={sensors?.offline??4} meta="ACTION NEEDED"/><Kpi icon={<TriangleAlert/>} label="Warning" value={sensors?.warning??2} meta="STALE / SUSPECT"/></div><div className="sensor-visual"><div className="panel sensor-health"><div className="panel-head"><div><h2>Network Pulse</h2><span>Telemetry activity over the last 60 minutes</span></div><Activity/></div><div className="pulse-bars">{Array.from({length:32},(_,i)=><i key={i} style={{height:`${25+Math.abs(Math.sin(i*1.7))*70}%`}}></i>)}</div></div><div className="panel coverage-card"><div className="coverage-ring"><strong>88%</strong><span>coverage</span></div><b>Good sensor coverage</b><small>4 offline · 2 stale · fallback risk logic active</small></div></div><div className="sensor-table">{(sensors?.items||[]).concat([{id:'SOIL-033',type:'SOIL_MOISTURE',location:'Cloud Hamlet',battery:63,signal:74,status:'ONLINE'},{id:'RIVER-009',type:'RIVER_LEVEL',location:'Riverbend',battery:81,signal:91,status:'ONLINE'}]).map(s=><div className="sensor-row" key={s.id}><div className={'sensor-dot '+s.status.toLowerCase()}></div><b>{s.id}</b><span>{s.type}</span><span>{s.location}</span><span>Battery <strong>{s.battery}%</strong></span><span>Signal <strong>{s.signal}%</strong></span><em>{s.status}</em></div>)}</div></main>}
function LandslidePage({loc,sim,busy,setSelected}){const sorted=[...(loc||[])].sort((a,b)=>(b.risk?.landslide_score||0)-(a.risk?.landslide_score||0));const [mode,setMode]=useState('slope');const [scan,setScan]=useState(true);useEffect(()=>{if(!scan)return;const t=setInterval(()=>{},1800);return()=>clearInterval(t)},[scan]);return <main><section className="page-head"><div><div className="eyebrow"><Mountain size={12}/> GEOHAZARD INTELLIGENCE</div><h1>Landslide Detection</h1><p>Monitor rainfall-triggered slope instability using simulated soil moisture, slope angle, ground movement, terrain exposure and historical hazard signals.</p></div><div className="ai-badge"><Mountain/>LANDSLIDE ENGINE</div></section><div className="landslide-command"><div className="landslide-radar"><div className="landslide-radar-grid"></div><div className={"landslide-scanline "+(scan?'running':'paused')}></div><div className="landslide-reticle"><span></span><b>HIMALAYAN SLOPE</b><small>LIVE SIMULATION SCAN</small></div><div className="scan-readout"><span>SCAN MODE</span><b>{mode.toUpperCase()}</b><small>Terrain tile · synthetic deformation layer</small></div><div className="landslide-controls"><button className={mode==='slope'?'active':''} onClick={()=>setMode('slope')}>Slope</button><button className={mode==='moisture'?'active':''} onClick={()=>setMode('moisture')}>Moisture</button><button className={mode==='movement'?'active':''} onClick={()=>setMode('movement')}>Movement</button><button onClick={()=>setScan(v=>!v)}>{scan?'Pause Scan':'Start Scan'}</button></div></div><div className="landslide-side"><div className="panel"><div className="panel-head"><div><h2>Priority Slopes</h2><span>Highest simulated landslide scores</span></div><TriangleAlert/></div>{sorted.slice(0,5).map(v=><button className="slope-row" key={v.id} onClick={()=>setSelected(v)}><div><b>{v.name}</b><small>{v.region} · {v.slope}° slope</small></div><strong>{v.risk.landslide_score}/100</strong><i className={v.risk.level.toLowerCase()}>{v.risk.level}</i></button>)}</div><button className="primary wide" disabled={busy} onClick={()=>sim('/api/simulation/landslide')}><Mountain size={16}/>Simulate Landslide Event</button></div></div><section className="landslide-method"><div><b>TRIGGER SIGNALS</b><span>Rainfall threshold · soil saturation · slope angle · ground movement · historical hazard</span></div><div><b>DETECTION OUTPUT</b><span>Village/ward score · confidence · explanation · alert state · evacuation readiness</span></div><div><b>OPTIONAL EXTENSIONS</b><span>InSAR deformation · geotechnical instruments · road vulnerability · route closures</span></div></section><p className="source-note">Demo implementation only. Real operational landslide thresholds and susceptibility models must be calibrated and validated by competent agencies.</p></main>}

function AlertPage({alerts,phone,setPhone,sendTest,sms,config}){return <main><section className="page-head"><div><div className="eyebrow">EVACUATION NOTIFICATION SYSTEM</div><h1>Alerts & SMS</h1><p>Automatic evacuation alerts are created when simulated risk crosses the emergency threshold.</p></div><div className={'sms-status '+(config?.live_sms?'live-sms':'demo-sms')}><MessageSquare/> {config?.live_sms?'TWILIO LIVE':'SIMULATED SMS'}</div></section><div className="sms-hero"><div><small>EMERGENCY CHANNEL</small><b>Twilio SMS Gateway</b><span>Escalation is deduplicated and cooldown-aware.</span></div><div className="sms-steps"><span>AI detects</span><ArrowUpRight/><span>Risk crosses threshold</span><ArrowUpRight/><span>SMS dispatched</span></div></div><div className="sms-layout"><div className="panel"><div className="panel-head"><div><h2>Alert history</h2><span>Deduplicated · escalation-aware</span></div></div>{alerts.length?<div>{alerts.map(a=><div className="alert-card" key={a.id}><div className={'alert-level '+a.level.toLowerCase()}>{a.level}</div><div><b>{a.village}</b><small>Risk {a.score}/100 · {a.status}</small><p>{a.message}</p></div><span className="sms-chip">SMS {a.sms}</span></div>)}</div>:<div className="empty">No active alerts. Use a simulation scenario to trigger one.</div>}</div><div className="panel test-box"><div className="panel-head"><div><h2>SMS test console</h2><span>Credentials stay server-side</span></div></div><label>Recipient phone number</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91XXXXXXXXXX"/><button className="primary wide" onClick={sendTest}><Phone size={16}/>Send test alert</button>{sms&&<div className="sms-result">{sms.status}<small>{sms.message_sid||sms.to||sms.detail}</small></div>}<div className="twilio-note"><b>Twilio integration</b><p>Set TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_FROM, SMS_RECIPIENTS and LIVE_SMS=true on the backend. Demo mode remains safe by default.</p></div></div></div></main>}

function SIHBlueprint(){
 const sources=[
  ['IMD','Real-time rain station data + forecasts','Weather observations and forecast inputs'],
  ['NASA GPM-IMERG','Satellite rainfall','Global precipitation estimates for gap filling'],
  ['GSI Bhukosh','Landslide inventory / susceptibility','Historical landslide and susceptibility context'],
  ['NRSC Bhuvan','DEM / terrain layers','CartoDEM, slope and watershed boundaries'],
  ['SMAP / GLDAS','Soil moisture','Root-zone moisture / saturation-trigger context']
 ];
 const tech=['Python','LSTM','FastAPI','PostGIS','MQTT / LoRaWAN','React dashboard','GSM SMS / IVR','Solar IoT nodes'];
 return <main>
  <section className="sih-hero">
   <div><div className="eyebrow"><Sparkles size={12}/> SMART INDIA HACKATHON 2026 · DISASTER MANAGEMENT</div><h1>GEO SHIELD AI</h1><p>Problem Statement ID <b>26192</b> · Flash Flood Prediction System for Hilly Regions using Multi-Source Data · Software · <b>Solver@SBU</b></p></div>
   <div className="sih-meta"><span>PS 26192</span><span>DISASTER MANAGEMENT</span><span>SOFTWARE</span><span>SOLVER@SBU</span></div>
  </section>

  <section className="sih-grid two">
   <div className="sih-card problem"><div className="sih-card-title">THE PROBLEM WE SOLVE</div><ul><li>Floods and landslides in hills can leave very little warning time.</li><li>Broad district-level alerts can be too coarse for one village or ward.</li><li>Monsoon events can damage homes, roads, crops and livelihoods.</li><li>The objective is to shift from reactive response toward earlier local preparedness.</li></ul></div>
   <div className="sih-card idea"><div className="sih-card-title">OUR IDEA — GEO SHIELD AI</div><ul><li>Fuse rain, soil, slope, river, satellite and historical hazard signals.</li><li>Update risk on a hyper-local grid with approximately 15-minute refresh cycles.</li><li>Generate flood + landslide risk for each village/ward area.</li><li>Deliver warnings through dashboard, siren/radio concepts, SMS/call and local-language workflows.</li></ul></div>
  </section>

  <section className="sih-section"><div className="section-title"><div><div className="eyebrow">DATA FOUNDATION</div><h2>Indian-grade multi-source inputs</h2></div><span>Public / authorized operational sources</span></div><div className="source-cards">{sources.map(([a,b,c])=><div className="source-card" key={a}><b>{a}</b><strong>{b}</strong><span>{c}</span></div>)}</div></section>

  <section className="sih-section"><div className="section-title"><div><div className="eyebrow">TECHNOLOGY</div><h2>Prototype technology stack</h2></div></div><div className="tech-chips">{tech.map(x=><span key={x}>{x}</span>)}</div></section>

  <section className="sih-section"><div className="section-title"><div><div className="eyebrow">METHODOLOGY & PROCESS</div><h2>Sense → Ingest → Learn → Decide → Deliver</h2></div><span>Hyper-local decision pipeline</span></div><div className="sih-pipeline">{[
   ['01','SENSE','Rain stations · satellites · soil sensors · slope maps · past disasters'],
   ['02','INGEST','Grid and clean data · map to ~1 km village grid · refresh ~15 min · fill gaps'],
   ['03','LEARN','AI core · LSTM-ready architecture · water-flow prediction · slope safety · danger score 0–100'],
   ['04','DECIDE','Alert engine · government colour codes · two-step escalation · officer approval for critical RED'],
   ['05','DELIVER','Village siren · radio · SMS / call · local language · app + district dashboard']
  ].map(([n,t,d])=><div key={n}><b>{n}</b><strong>{t}</strong><span>{d}</span></div>)}</div></section>

  <section className="sih-grid two">
   <div className="sih-card validation"><div className="sih-card-title">BUILD & VALIDATION PLAN</div><div className="validation-steps"><div><b>1</b><span>Train/test with about 10 years of rainfall + disaster records.</span></div><div><b>2</b><span>Pilot in one hill district, such as Rudraprayag.</span></div><div><b>3</b><span>Measure warning hours gained, misses and false alarms.</span></div><div><b>4</b><span>Grow state-by-state with disaster-response practice drills.</span></div></div></div>
   <div className="sih-card feasibility"><div className="sih-card-title">FEASIBILITY</div><ul><li>Uses established rainfall, terrain and landslide science.</li><li>Leverages available Indian geospatial/weather datasets where access is authorized.</li><li>Concept estimate: one solar sensor box around ₹12–15k, with valley-level deployment sized to local terrain and coverage.</li><li>Solar + radio/LoRa mesh is intended to remain resilient during storm-related network cuts; the concept targets up to 48 hours of continuity.</li><li>Designed to connect with disaster-management control rooms and existing alert infrastructure such as Sachet/CAP, subject to authorized integration.</li></ul></div>
  </section>

  <section className="sih-section"><div className="section-title"><div><div className="eyebrow">CHALLENGES → STRATEGIES</div><h2>Designed for Himalayan field constraints</h2></div></div><div className="challenge-grid"><div><b>Few sensors in far valleys</b><span>→ Satellite rainfall + AI fill data gaps.</span></div><div><b>Power / network cuts</b><span>→ Solar + radio/LoRa mesh concepts keep field sensing resilient.</span></div><div><b>False-alarm fatigue</b><span>→ Two-step escalation and officer approval for critical RED alerts.</span></div><div><b>Hard maintenance in hills</b><span>→ Self-checking boxes + trained village volunteers.</span></div></div></section>

  <section className="sih-impact"><div><strong>6–12 hrs</strong><span>target warning lead time</span></div><div><strong>~1 km²</strong><span>target village / ward grid</span></div><div><strong>₹0*</strong><span>target additional alert cost using existing channels</span></div><div><strong>12 states*</strong><span>potential notified hill-state scale</span></div></section>
  <p className="sih-footnote">*Project targets/design goals from the SIH concept document, not measured production results. Real deployment cost, warning lead time, coverage and state rollout require field validation and authorized integration.</p>

  <section className="sih-concept-notes"><div><b>CONCEPT DOCUMENT FRAMING</b><span>The SIH concept positions village-level warning, combined flood + landslide intelligence, and operation beyond continuous internet as core differentiators. Claims such as “first of its kind” should be treated as a project positioning claim and benchmarked against existing systems before deployment.</span></div><div><b>RESPONSE MODEL</b><span>The project goal is anticipatory decision support: detect signals earlier, prepare communities and responders, and connect warnings to action rather than waiting for post-event response.</span></div></section><section className="sih-impact-categories"><div><b>SOCIAL</b><span>Save lives · planned evacuation · faster reopening of schools and clinics</span></div><div><b>ECONOMIC</b><span>Reduce damage to crops, roads and homes · support resilient hill economies</span></div><div><b>ENVIRONMENTAL</b><span>Support safer land use · protect river and forest zones</span></div><div><b>OPERATIONAL</b><span>Prepare responders before escalation · unified control-room view · practice drills</span></div></section>

  <section className="sih-section references"><div className="section-title"><div><div className="eyebrow">RESEARCH & REFERENCES</div><h2>Evidence base used by the concept</h2></div></div><div className="reference-grid"><div><b>DATASETS & PLATFORMS</b><span>IMD · NRSC Bhuvan · GSI Bhukosh · NASA GPM-IMERG · SMAP / GLDAS</span></div><div><b>MODELS & GUIDELINES</b><span>Kratzert et al. (2019) · USGS TRIGRS / Iverson · van Westen et al. · NDMA guidelines · Sachet / CAP protocol</span></div></div></section>

  <section className="sih-unique"><div><div className="eyebrow"><ShieldCheck size={12}/> WHY IT MATTERS</div><h2>Seconds of warning become a structured path to action.</h2><p>Geo Shield AI is a decision-support prototype. It does not replace official warnings from IMD, NDRF, DDMA, SDMA or other competent authorities.</p></div><div className="unique-flow"><span>DATA</span><i>→</i><span>INTELLIGENCE</span><i>→</i><span>WARNING</span><i>→</i><span>ACTION</span></div></section>
 </main>
}

function Detail({v,close}){return <div className="modal"><div className="detail"><button className="close" onClick={close}>×</button><div className={'bigstatus '+v.risk.level.toLowerCase()}>{v.risk.level}</div><div className="eyebrow">AI VILLAGE ASSESSMENT</div><h1>{v.name}</h1><div className="detail-score">{v.risk.score}<small>/100</small></div><p className="simple">{v.risk.simple_explanation}</p><div className="metrics"><span><CloudRain/>Rain<strong>{v.rain} mm/h</strong></span><span><Droplets/>Soil<strong>{v.soil}%</strong></span><span><Mountain/>Slope<strong>{v.slope}°</strong></span><span><Waves/>River<strong>{v.river}%</strong></span></div><h3>Why the AI escalated</h3><div className="contributors">{v.risk.explanation.map(x=><div key={x}>+ {x}</div>)}</div><div className="coverage"><b>Data coverage {v.risk.coverage}%</b><span>{v.risk.confidence} confidence · demo model</span></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
